#!/bin/bash

set -eu

dotfile_dir="${HOME}/.dotfiles"

if [ -d $dotfile_dir ]; then
  echo "dotfiles have been already installed to '${dotfile_dir}'."
  exit 0
fi

git clone -q git@github.com:miniturbo/dotfiles.git $dotfile_dir

PATH="${dotfile_dir}/bin:${PATH}"

dotfile install
