[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'jlanzarotta/bufexplorer'
hook_add = '''
  let g:bufExplorerShowRelativePath=1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call marble#lightline#init()'

#[[plugins]]
#repo = 'edkolev/tmuxline.vim'
#hook_add = '''
#  let g:tmuxline_theme  = 'lightline'
#  let g:tmuxline_preset = 'marble'
#'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  let g:hybrid_custom_term_colors = 1
  "let g:hybrid_reduced_contrast   = 1
  colorscheme hybrid
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

#[[plugins]]
#repo = 'dense-analysis/ale'
#hook_add = '''
#  let g:ale_fix_on_save = 2
#  let g:ale_fixers = ['eslint']
#  let g:ale_sign_column_always = 1
#  let g:ale_sign_error = '✖'
#  let g:ale_sign_warning = '⚠'
#
#  autocmd ColorScheme *
#    \ hi clear ALEErrorSign |
#    \ hi clear ALEWarningSign |
#    \ highlight ALEErrorSign ctermbg=NONE ctermfg=red |
#    \ highlight ALEWarningSign ctermbg=NONE ctermfg=yellow |
#'''
