#!/bin/bash

set -eu

root_dir=$(cd "$(dirname $0)/.." && pwd)
platform=$(uname | tr '[A-Z]' '[a-z]')

mitamae_version="1.14.0"
mitamae_cache="mitamae-${mitamae_version}"

case $platform in
  "darwin")
    mitamae_bin="mitamae-x86_64-darwin"
    mitamae_command="${root_dir}/bin/mitamae"
    ;;
  "linux")
    mitamae_bin="mitamae-x86_64-linux"
    mitamae_command="sudo -E ${root_dir}/bin/mitamae"
    ;;
esac

if [ ! -f "${root_dir}/bin/${mitamae_cache}" ]; then
  echo "Downloading mitamae ${mitamae_version}..."
  curl -o "${root_dir}/bin/${mitamae_cache}" -fsSL "https://github.com/itamae-kitchen/mitamae/releases/download/v${mitamae_version}/${mitamae_bin}"
  chmod +x "${root_dir}/bin/${mitamae_cache}"
fi

ln -snf $mitamae_cache "${root_dir}/bin/mitamae"

$mitamae_command local -y ${root_dir}/nodes/${platform}.yml ${root_dir}/entry.rb
