#!/bin/bash

set -eu

root_dir=$(cd "$(dirname $0)/.." && pwd)

mitamae_version="1.4.5"
mitamae_cache="mitamae-${mitamae_version}"

if [ ! -f "${root_dir}/bin/${mitamae_cache}" ]; then
  echo "Downloading mitamae ${mitamae_version}..."
  curl -o "${root_dir}/bin/${mitamae_cache}" -fsSL "https://github.com/itamae-kitchen/mitamae/releases/download/v${mitamae_version}/mitamae-x86_64-darwin"
  chmod +x "${root_dir}/bin/${mitamae_cache}"
fi

ln -snf $mitamae_cache "${root_dir}/bin/mitamae"

${root_dir}/bin/mitamae local ${root_dir}/roles/darwin/default.rb
