#!/bin/bash

set -e

root_dir=$(cd "$(dirname $0)/.." && pwd)
command="$1"

PATH="${root_dir}/libexec:${PATH}"

case $command in
  "" | "-h" | "--help")
    exec $(command -v "dotfile-help")
    ;;
  "-v" | "--version")
    exec $(command -v "dotfile-version")
    ;;
  *)
    command_path="$(command -v "dotfile-$command" || true)"
    if [ -z "$command_path" ]; then
      echo "dotfile: no such command '$command'" >&2
      exit 1
    fi

    exec $command_path
    ;;
esac
