#!/bin/bash

set -eu

root_dir=$(cd "$(dirname $0)/.." && pwd)
platform=$(uname | tr '[A-Z]' '[a-z]')

mitamae_version="1.9.0"
mitamae_cache="mitamae-${mitamae_version}"

if [ ! -f "${root_dir}/bin/${mitamae_cache}" ]; then
  case $platform in
    "darwin") mitamae_bin="mitamae-x86_64-darwin" ;;
    "linux")  mitamae_bin="mitamae-x86_64-linux"  ;;
  esac

  echo "Downloading mitamae ${mitamae_version}..."
  curl -o "${root_dir}/bin/${mitamae_cache}" -fsSL "https://github.com/itamae-kitchen/mitamae/releases/download/v${mitamae_version}/${mitamae_bin}"
  chmod +x "${root_dir}/bin/${mitamae_cache}"
fi

ln -snf $mitamae_cache "${root_dir}/bin/mitamae"

case $platform in
  "darwin")  ${root_dir}/bin/mitamae local "${root_dir}/roles/$platform/default.rb" ;;
  *) sudo -E ${root_dir}/bin/mitamae local "${root_dir}/roles/$platform/default.rb" ;;
esac
